#!/usr/bin/python3
def raise_exception_msg(message=""):
    try:
        return s
    except NameError:
        print(message)
